language: node_js
sudo: required
dist: trusty
before_script:
- npm install -g bower web-component-tester polylint
- bower install
- polylint
node_js: 6
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
script:
- xvfb-run wct
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct -s 'default'; fi
env:
  global:
  - secure: lrbCdtCmSweKAJecA0iTxgsneyGECgPvmaudsAOKgDSXCg/ZDRv773bi3UOw+TdpC9HGMIJQKBpHeoye5nEspVUACwJzYpY81zxyaHJOH0MjofoXyKNPZfCvsmT7iELttE9r9LmOX9I/LXj7RughAbCFf6e4KIzkHlU24sKhzZM=
  - secure: dZL82ebH0J17Exd0DU0YmEf2SuAxk98KR6uMdEvkFcuhlOemfWDQZAl5m/3bLXcqLGKUt+AKSfDyWWV7mX/G+Prza7qGEEJ/gBVfkbiBHcDRy6CIESrzb/4DWhRvX6n5PzDZpnnznxwbDf6wWriVagbz0TW4FeRgC72XgO/Z0AI=
