language: node_js
sudo: required
dist: trusty
before_script:
- npm install -g bower web-component-tester
- bower install
- polylint
node_js: 6
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
script:
- xvfb-run wct
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct -s 'default'; fi
env:
  global:
  - secure: lrbCdtCmSweKAJecA0iTxgsneyGECgPvmaudsAOKgDSXCg/ZDRv773bi3UOw+TdpC9HGMIJQKBpHeoye5nEspVUACwJzYpY81zxyaHJOH0MjofoXyKNPZfCvsmT7iELttE9r9LmOX9I/LXj7RughAbCFf6e4KIzkHlU24sKhzZM=
  - secure: VqqvCOOsjsdYa3OBqMU2Xo3qyByMg0vFlnig0XvY/ymSVEcUa6r4HVd2fja7EQLdEAQA0v/OFt050fc0m1Zc1ni0pcmNwWm/kRUUlksmA0XcSPJprx0yWpVZuuQX/frKm7Lj2bDFPuDN9e0IXb2CFQP0ba6d4qW7u1rSjLfoIAQ=
